DEBOUNCE_TYPE = sym_defer_pk

ENCODER_MAP_ENABLE = yes
AUTO_SHIFT_ENABLE = no

CAPS_WORD_ENABLE = yes
COMMAND_ENABLE = no
REPEAT_KEY_ENABLE = no
AUDIO_ENABLE = no
LAYER_LOCK_ENABLE = yes
COMBO_ENABLE = yes
EXTRAKEY_ENABLE = yes
RAW_ENABLE = yes
MOUSEKEY_ENABLE = yes
KEYBOARD_SHARED_EP = yes
MOUSE_MAP_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes

CONSOLE_ENABLE = yes
